### ISSUE TITLE
ERRO[0000] failed to handle profile: Operation cannot be fulfilled

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-profile-state-controller#1]
> One thing I'm not sure about is this error I get sometimes:
> ```
> ERRO[0000] failed to handle profile: Operation cannot be fulfilled on profiles.kubeflow.org "bob": the object has been modified; please apply your changes to the latest version and try again  source="controller.go:182"
> E0411 18:51:10.720692   20285 controller.go:155] error synching "bob/pod-false": Operation cannot be fulfilled on profiles.kubeflow.org "bob": the object has been modified; please apply your changes to the latest version and try again, requeing
> ```

**Comment by justbert** [comment]
It means that since the controller received the object to modify, it has been modified and as such, the server is refusing your updates since you aren't working from the latest version of the object. This is usually handled by checking the **metadata.resourceVersion**.

**Comment by justbert** [comment]
https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions

**Comment by blairdrummond** [comment]
Thanks @justbert ! I figured it was something like that. Btw we'll have to show you the "SAS controller" design once the last few components are done! I think you'll like it
