### ISSUE TITLE
Align with repo standards

### ISSUE THREAD

**Issue by sylus** [StatCan/aaw-profile-state-controller#5]
Hey @saffaalvi 

Can this align with the other controller standards?

https://github.com/StatCan/aaw-inferenceservices-controller

- [x]  Put k3d yaml in cluster folder
- [x] Use taskfile instead of make
- [x] Add back github workflows to build container
- [x] License should be License.md
- [x] Add proper tags and repo description
- [x] Binary should not be committed

When all of this is done add to the component to the DAaaS main readme.md

**Comment by saffaalvi** [comment]
@sylus I've made the changes, please check them over and let me know if anything needs to be changed/added.

**Comment by sylus** [comment]
Thanks so much @saffaalvi super appreciated :) 

I think i have one or two to update myself as well!
